--           Krait Config           
-- Automatically generated by Krait 
--      READ THE DOCUMENTATION      
local c = krait.config

c.git = "https://github.com/m1ten/krait"
c.author = "miten <57693631+m1ten@users.noreply.github.com>"
c.name = "krait"
c.dir = "C:\\Users\\miten\\krait"
c.ver = "0.0.1"
c.license = "Apache-2.0"
c.repos = {"https://github.com/m1ten/krait-pkgs"}
c.desc = "cross platform package manager"
