
--           Krait Config           --
-- Automatically generated by Krait --
--      READ THE DOCUMENTATION      --

local c = krait.config

c.name = "krait"
c.author = "<user> <email>"
c.ver = "0.0.1"
c.desc = "cross platform package manager"
c.license = "Apache-2.0"
c.git = "https://github.com/m1ten/krait"
c.pkgs = {}

-- Feel free to modify the following lines --

c.dir = "/home/krait"
c.repos = { "https://github.com/m1ten/kraits" }
c.args = {}